---
- name: "Install Nvim 0.95 Prereqs"
  apt:
    name: ["ninja-build", "gettext", "cmake", "unzip", "curl"]
    state: present
  become: true
- name: "Get Nvim 0.95 Source"
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage
    dest: "{{ nvim_source_path }}"
- name: "Install Nvim"
  ansible.builtin.shell:
    chdir: "{{nvim_source_path}}"
    cmd: "chmod u+x nvim.appimage"
- name: "Expose Nvim Globally"
  ansible.builtin.shell:
    chdir: "{{nvim_source_path}}"
    cmd: "sudo mkdir -p /opt/nvim && sudo mv nvim.appimage /opt/nvim/nvim"
- name: "Add Nvim to PATH"
  ansible.builtin.shell:
    cmd: "echo 'export PATH=$PATH:/opt/nvim' >> ~/.zshrc"
- name: "Copy AstroNvim"
  git:
    repo: "https://github.com/glorisonlai/astronvimv4_config.git"
    dest: "{{ nvim_config_path }}"
    depth: 1
# name: "Install Plugins"
# shell: "nvim --cmd PlugInstall"
# Figure out how to close file
# name: "Install TS"
