---
- name: "Install Nvim 0.95 Prereqs"
  apt:
    name: ["ninja-build", "gettext", "cmake", "unzip", "curl"]
    state: present
  become: true
- name: "Get Nvim 0.95 Source"
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage
    dest: "{{ nvim_source_path }}"
- name: "Install Nvim"
  ansible.builtin.shell:
    chdir: "/home/vagrant"
    cmd: "chmod u+x neovim"
- name: "Expose Nvim Globally"
  ansible.builtin.shell:
    chdir: "/home/vagrant"
    cmd: "sudo mkdir -p /opt/nvim && sudo cp neovim /opt/nvim/nvim"
- name: "Add Nvim to PATH"
  ansible.builtin.shell:
    cmd: "echo 'export PATH=$PATH:/opt/nvim' >> ~/.zshrc"
- name: "Copy AstroNvim"
  ansible.builtin.git:
    repo: "https://github.com/AstroNvim/template"
    dest: "{{ nvim_config_path }}"
    force: true
