---
# tasks file for install-docker
- name: "Install Docker Apt Repo prereqs"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
  become: true
- name: "Create directory for Docker's GPG key"
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    mode: "0755"
  become: true
- name: "Add Docker's official GPG key"
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
  become: true
- name: "Add All Read permissions"
  ansible.builtin.file:
    path: "/etc/apt/keyrings/docker.asc"
    mode: a+r
  become: true

- name: "Print architecture variables"
  ansible.builtin.debug:
    msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

# - name: "Add Docker repository"
#   ansible.builtin.apt_repository:
#     repo: >-
#       "deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
#       signed-by=/etc/apt/keyrings/docker.asc]
#       https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
#     filename: docker
#     state: present
- name: "Add Docker Repo"
  ansible.builtin.shell:
    cmd: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'

- name: "Install Docker and related packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  become: true

- name: "Add Docker group"
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: "Add user to Docker group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: "Enable and start Docker services"
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service
  become: true
